### ISSUE TITLE
preflight request failed with status 404

### ISSUE THREAD

**Issue by banduric** [MicroFocus/octane-gitlab-service#29]
When sending test artifact to ALM Octane preflight request fails with status 404
preflight request is https://octane.server.net/internal-api/shared_spaces/12001/analytics/ci/servers/GitLab-API/jobs/path%2Fto%2Fapplication%2Ftest/tests-result-preflight

jobId is path%2Fto%2Fapplication%2Ftest, not sure if this is correct to use in Octane API

`com.hp.octane.integrations.exceptions.PermanentException: preflight request failed with status 404. JobId: 'path/to/application/test'. Request URL : https://...truncated..../tests-result-preflight
	at com.hp.octane.integrations.services.tests.TestsServiceImpl.isTestsResultRelevant(TestsServiceImpl.java:134) ~[integrations-sdk-2.6.3.22.jar!/:?]
	at com.hp.octane.integrations.services.tests.TestsServiceImpl.doPreflightAndPushTestResult(TestsServiceImpl.java:280) ~[integrations-sdk-2.6.3.22.jar!/:?]
	at com.hp.octane.integrations.services.tests.TestsServiceImpl.worker(TestsServiceImpl.java:249) ~[integrations-sdk-2.6.3.22.jar!/:?`

**Comment by radislavB** [comment]
resolved
